apiVersion: v1
kind: Service
metadata:
  name: {{ template "private-ethereum.fullname" . }}-miner-service
  labels:
    app: {{ template "private-ethereum.name" . }}-miner-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "private-ethereum.name" . }}-miner
  type: NodePort
  ports:
  ports:
    - name: miner-jsonrpc
      protocol: TCP
      port: 8545
      targetPort: 8545
      nodePort: 30001
    - name: miner-wsrpc
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: miner-ipc-listen
      protocol: UDP
      port: 30301
      targetPort: 30301
    - name: miner-ipc-discovery
      protocol: TCP
      port: 30303
      targetPort: 30303
      nodePort: 30002
