apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "geth.fullname" . }}-config
  labels:
    app: {{ template "geth.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  genesis.json: |
{{ .Files.Get "genesis.json" | indent 4 }}
