
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  name = "github.com/dfinity/go-dfinity-crypto"
  revision = "1cfc23c8f712378febdf621f27e49dd67846e901"
  source = "https://github.com/keep-network/go-dfinity-crypto.git"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  revision = "b26d9c308763d68093482582cea63d69be07a0f0"
  source = "https://github.com/keep-network/toml.git"

[[constraint]]
  name = "golang.org/x/sys"
  revision = "7dfd1290c7917b7ba22824b9d24954ab3002fe24"

[[constraint]]
  name = "github.com/urfave/cli"
  revision = "8e01ec4cd3e2d84ab2fe90d8210528ffbb06d8ff"
  source = "https://github.com/keep-network/cli.git"
