kind: ConfigMap
apiVersion: v1
metadata:
  name: eth-network-ropsten
  namespace: default
data:
  rpc-hostname: http://eth-tx-ropsten.test.keep.network
  ws-hostname: ws://eth-tx-ropsten.test.keep.network
  rpc-port: '8545'
  ws-port: '8546'
  network-id: '3'
  contract-owner-eth-account-address: '0x923c5dbf353e99394a21aa7b67f3327ca111c67d'
