version: 2
jobs:
  test_solidity:
    docker:
      - image: circleci/node:latest
    steps:
        - checkout
        - run: cd solidity && npm install && npm run test && npm run posttest

workflows:
  version: 2
  solidity:
    jobs:
      - test_solidity
