version: 2
jobs:
  test_solidity:
    docker:
      - image: circleci/node:latest
    steps:
        - checkout
        - run: sudo npm install -g ethereumjs-testrpc
        - run:
            name: Running testrpc
            command: testrpc
            background: true  
        - run: cd solidity && npm install && npm run test

workflows:
  version: 2
  solidity:
    jobs:
      - test_solidity
