version: 2
jobs:
  test_solidity:
    docker:
      - image: circleci/node:latest
    steps:
        - checkout
        - run: echo "test"
  build_client:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build .
  generate_docs:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run: |
          cd docs
          make clean
          mkdir -p /tmp/docs/img
          make docs
          cp relay-states.pdf /tmp/docs
          cp -r img/generated /tmp/docs/img/generated
      - save_cache:
          key: docs-cache
          paths:
            - /tmp/docs
  upload_docs:
    docker:
      - image: google/cloud-sdk:slim
    steps:
      - checkout
      - restore_cache:
          key: docs-cache
      - run: |
          echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ~/gcloud-service-key.json
          gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
          gcloud config set project cfc-production
          cd /tmp/docs
          gsutil -m cp -r * gs://docs.keep.network/$CIRCLE_BRANCH/


workflows:
  version: 2
  solidity:
    jobs:
      - test_solidity
  docs:
    jobs:
      - generate_docs
      - upload_docs
  go:
    jobs:
      - build_client
