version: 2
jobs:
  test_solidity:
    docker:
      - image: circleci/node:latest
    steps:
        - checkout
        - run: sudo npm install -g ethereumjs-testrpc
        - run:
            name: Running testrpc
            command: testrpc
            background: true  
        - run: cd solidity && npm install && npm run test
  build_client:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker build .
  generate_docs:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run: |
          cd docs
          make clean
          mkdir -p /tmp/docs
          make relay-states.pdf
          cp relay-states.pdf /tmp/docs
      - store_artifacts:
          path: /tmp/docs

workflows:
  version: 2
  solidity:
    jobs:
      - test_solidity
  docs:
    jobs:
      - generate_docs
  go:
    jobs:
      - build_client
