version: 2
jobs:
  test_solidity:
    docker:
      - image: circleci/node:latest
    steps:
        - checkout
        - run: echo "test"

workflows:
  version: 2
  solidity:
    jobs:
      - test_solidity
