version: 2
jobs:
  test_solidity:
    docker:
      - image: circleci/node:latest
    steps:
        - checkout
        - run: echo "test"
  generate_docs:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run: |
          cd docs
          make clean
          mkdir -p /tmp/docs
          make relay-states.pdf
          cp relay-states.pdf /tmp/docs
      - store_artifacts:
          path: /tmp/docs

workflows:
  version: 2
  solidity:
    jobs:
      - test_solidity

  docs:
    jobs:
      - generate_docs
