apiVersion: 1
datasources:
  - name: Trickster
    type: prometheus
    access: proxy
    editable: true
    orgId: 1
    url: http://trickster:8480
    version: 1
    isDefault: true

  - name: Prometheus
    type: prometheus
    access: proxy
    editable: true
    orgId: 1
    url: http://prometheus:9090
    version: 1
