# This is a TOML configuration file for DKG, P2P networking and connection to Ethereum

# Provider Initialization Example

[ethereum]
  URL                = "ws://10.102.100.98:8546"
  URLRPC             = "http://10.102.100.98:8545"

[ethereum.account]
  Address            = "0x415650a368157dec773cc556965856188c6ca84a"
  KeyFile            = "/mnt/eth-data/eth-keyfile"

[ethereum.ContractAddresses]
  # Hex-encoded address of KeepRandomBeacon contract
  KeepRandomBeacon = "0xb913b3d6E14B51e45062113C2e7b6d83955a231A"
  # Hex-encoded address of KeepGroup contract
  KeepGroup = "0xAA8EBDedE631f8a38F8F27475B724acdbf7A3b1c"
  # StakingProxy
  Staking = "0x22DEe6b2d61Afa48EFeFc494780a501Ab1605d44"

[LibP2P]
  Peers = ["/ip4/10.102.100.142/tcp/3919/ipfs/16Uiu2HAkzJ9a9DNJs1q82EHDYUZgFwuhAhBG2eijoDrQFhqJ8yAC"]
  Port = 3923
