# This is a TOML configuration file for DKG, P2P networking and connection to Ethereum

# Provider Initialization Example

[ethereum]
  URL                = "ws://eth-tx-node.default.svc.cluster.local:8546"
  URLRPC             = "http://eth-tx-node.default.svc.cluster.local:8545"

[ethereum.account]
  Address            = "0xc82C480E82Ee76Ae607a3446CAc22314FaBdD19e"
  KeyFile            = "/mnt/eth-data/eth-keyfile"

[ethereum.ContractAddresses]
  # Hex-encoded address of KeepRandomBeacon contract
  KeepRandomBeacon = "0x439f517ccb968e5cb4Bb48B6888645C57906B084"
  # Hex-encoded address of KeepGroup contract
  KeepGroup = "0xAb5D2d616EB717cA527a946517eA70Fdc3e3D55b"
  # StakingProxy
  Staking = "0xca59725bC84196e90BBE295460Ae90f11164Fe13"

[LibP2P]
  Peers = ["/ip4/10.102.100.142/tcp/3919/ipfs/16Uiu2HAm9RGTm8VGne5PvZGAw9KYNDggHaEQh5wiGSKgibp2G95r"]
  Port = 3923
