# This is a TOML configuration file for DKG, P2P networking and connection to Ethereum

# Provider Initialization Example

[ethereum]
  URL                = "ws://eth-tx-node.default.svc.cluster.local:8546"
  URLRPC             = "http://eth-tx-node.default.svc.cluster.local:8545"

[ethereum.account]
  Address            = "0xc82C480E82Ee76Ae607a3446CAc22314FaBdD19e"
  KeyFile            = "/mnt/eth-data/eth-keyfile"

[ethereum.ContractAddresses]
  # Hex-encoded address of KeepRandomBeaconFrontend contract
  KeepRandomBeaconFrontend = "0x9d28652e7777946a5Cf1E738E38024cb14993be9"
  # Hex-encoded address of KeepRandomBeaconOperator contract
  KeepRandomBeaconOperator = "0xc9e8CA4765A797C2d614a87de000b35240b86610"
  # StakingProxy
  Staking = "0xC3920F936b251DFE4B4b62C3b62FB530D032a090"

[LibP2P]
  Peers = ["/ip4/10.102.100.142/tcp/3919/ipfs/16Uiu2HAm9RGTm8VGne5PvZGAw9KYNDggHaEQh5wiGSKgibp2G95r"]
  Port = 3923
