---
apiVersion: v1
kind: Service
metadata:
  name: trickster
spec:
  selector:
    app: trickster
  type: NodePort
  ports:
    - port: 8480
      targetPort: trickster
    - port: 8481
      targetPort: metrics
