---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keep-staking-dapp-http
  namespace: staking-dapp
  labels:
    app: staking-dapp
    type: dapp
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
spec:
  backend:
    # This assumes service eth-dashboard-http exists and routes to healthy endpoints
    serviceName: keep-staking-dapp-http
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: keep-dapp-staking
  labels:
    app: keep-dapp
    type: staking
spec:
  ports:
  - port: 80
    targetPort: 80
    name: tcp-80
  selector:
    app: keep-dapp
    type: staking