---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keep-client-0
  namespace: default
  labels:
    app: keep
    type: client
    id: "0"
    network: goerli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keep
      type: client
      id: "0"
  serviceName: keep-client-0
  volumeClaimTemplates:
    - metadata:
        name: keep-client-data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 512Mi
  template:
    metadata:
      labels:
        app: keep
        type: client
        id: "0"
        network: goerli
    spec:
      volumes:
        - name: keep-client-data
          persistentVolumeClaim:
            claimName: keep-client-data
        - name: eth-account-keyfile
          configMap:
            name: eth-account-info
            items:
              - key: account-0-keyfile
                path: account-0-keyfile
      containers:
        - name: keep-client-0
          image: gcr.io/keep-test-f3e0/keep-client
          imagePullPolicy: Always
          ports:
            - containerPort: 3919
          env:
            - name: KEEP_ETHEREUM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eth-account-passphrases
                  key: account-0
            - name: LOG_LEVEL
              value: debug
            - name: IPFS_LOGGING_FMT
              value: nocolor
            - name: ETH_WS_URL
              valueFrom:
                secretKeyRef:
                  name: eth-network-goerli
                  key: ws-url
          volumeMounts:
            - name: keep-client-data
              mountPath: /mnt/keep-client/data
            - name: eth-account-keyfile
              mountPath: /mnt/keep-client/keyfile
          command:
            [
              "keep-client",
              "--ethereum.url",
              "$(ETH_WS_URL)",
              "--ethereum.key",
              "/mnt/keep-client/keyfile/account-0-keyfile",
              "--storage.dataDir",
              "/mnt/keep-client/data",
              "--network.port",
              "3919",
              "--network.announcedAddresses",
              "/dns4/bootstrap-0.test.keep.network/tcp/3919",
              "--network.peers",
              "/dns4/bootstrap-1.core.keep.test.boar.network/tcp/3001/ipfs/16Uiu2HAkuTUKNh6HkfvWBEkftZbqZHPHi3Kak5ZUygAxvsdQ2UgG",
              "--metrics.port",
              "9601",
              "start",
            ]

      initContainers:
        - name: initcontainer-ecdsa-hardhat
          image: gcr.io/keep-test-f3e0/ecdsa-hardhat
          imagePullPolicy: Always
          env:
            - name: CHAIN_API_URL
              valueFrom:
                secretKeyRef:
                  name: eth-network-goerli
                  key: rpc-url
            - name: CONTRACT_OWNER_ETH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: eth-network-goerli
                  key: contract-owner-eth-account-private-key
            - name: KEEP_CLIENT_ETH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: eth-account-privatekeys
                  key: account-0
            - name: ACCOUNTS_PRIVATE_KEYS
              value: $(CONTRACT_OWNER_PRIVATE_KEY),$(KEEP_CLIENT_ETH_PRIVATE_KEY)
            - name: KEEP_CLIENT_ETH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eth-account-info
                  key: account-0-address
          command:
            [
              "initialize",
              "--owner",
              "$(KEEP_CLIENT_ETH_ADDRESS)",
              "--provider",
              "$(KEEP_CLIENT_ETH_ADDRESS)",
              "--operator",
              "$(KEEP_CLIENT_ETH_ADDRESS)",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: keep-client-0
  namespace: default
  labels:
    app: keep
    type: client
    id: "0"
spec:
  type: LoadBalancer
  ports:
    - port: 3919
      targetPort: 3919
      name: tcp-3919
    - port: 9601
      targetPort: 9601
      name: tcp-9601
  selector:
    app: keep
    type: client
    id: "0"
