[ethereum]
  URL = "https://ropsten.infura.io/v3/59fb36a36fa4474b890c13dd30038be5"
  URLRPC = "https://ropsten.infura.io/v3/59fb36a36fa4474b890c13dd30038be5"

  [ethereum.account]
    Address = "0x7fb43a257bf74904a41506fe38c87d32d91a77ae"
    KeyFile = "/mnt/keep-client/config/eth_account_keyfile"

  [ethereum.ContractAddresses]
    # Hex-encoded address of KeepRandomBeaconOperator contract
    KeepRandomBeaconOperator = "0xd827DBbb5E70249B15Fa06C16072F91300b122bF"
    # TokenStaking
    TokenStaking = "0xDFCD401cCFf45Ad92e7091fc0e21157500D0673a"
    # Hex-encoded address of KeepRandomBeaconService contract. Only needed
    # in cases where the client's utility functions will be used (e.g., the
    # relay subcommand).
    KeepRandomBeaconService = "0x3f3da6d75392bC36FD75dC31342B1E213EA992E0"

[LibP2P]
  Peers = ["/ip4/10.102.1.94/tcp/3919/ipfs/16Uiu2HAmHT8KUYvA2a83YH6JjaV7pz1C8gVVE7eUREae3KAGCzrX"]
  Port = 3919
  # AnnouncedAddresses:
  # Leaving AnnouncedAddresses empty will set a default address to be
  # announced to the network.  The default address will vary by deploy
  # conditions.  Set AnnouncedAddresses if you have known external IPs
  # or DNS entries you want to route traffic through.
  AnnouncedAddresses = []

[Storage]
  DataDir = "/mnt/keep-client/data"