---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keep-client-2
  namespace: default
  labels:
    app: keep
    type: client
    id: "2"
    network: goerli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keep
      type: client
      id: "2"
  serviceName: keep-client-2
  volumeClaimTemplates:
    - metadata:
        name: keep-client-data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 512Mi
  template:
    metadata:
      labels:
        app: keep
        type: client
        id: "2"
        network: goerli
    spec:
      volumes:
        - name: keep-client-data
          persistentVolumeClaim:
            claimName: keep-client-data
        - name: eth-account-keyfile
          configMap:
            name: eth-account-info
            items:
              - key: account-2-keyfile
                path: account-2-keyfile
      containers:
        - name: keep-client
          image: gcr.io/keep-test-f3e0/keep-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3919
          env:
            - name: KEEP_ETHEREUM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eth-account-passphrases
                  key: account-2
            # Read secret to env variable to use it as arg.
            - name: ETH_WS_URL
              valueFrom:
                secretKeyRef:
                  name: eth-network-goerli
                  key: ws-url
          envFrom:
            - configMapRef:
                name: keep-client-config
          volumeMounts:
            - name: keep-client-data
              mountPath: /mnt/keep-client/data
            - name: eth-account-keyfile
              mountPath: /mnt/keep-client/keyfile
          command: ["keep-client", "start"]
          args:
            [
              "--ethereum.url",
              "$(ETH_WS_URL)",
              "--ethereum.keyFile",
              "/mnt/keep-client/keyfile/account-2-keyfile",
              "--storage.dataDir",
              "/mnt/keep-client/data",
              "--network.port",
              "3919",
              "--network.announcedAddresses",
              "/dns4/keep-client-2.default.svc.cluster.local/tcp/3919",
              "--network.peers",
              "/dns4/keep-client-1.default.svc.cluster.local/tcp/3919/ipfs/16Uiu2HAm3eJtyFKAttzJ85NLMromHuRg4yyum3CREMf6CHBBV6KY",
              "--metrics.port",
              "9601",
              "--diagnostics.port",
              "9701",
            ]
      initContainers:
        - name: initcontainer
          image: gcr.io/keep-test-f3e0/keep-ecdsa-hardhat:latest
          imagePullPolicy: Always
          env:
            - name: CHAIN_API_URL
              valueFrom:
                secretKeyRef:
                  name: eth-network-goerli
                  key: http-url
            - name: CONTRACT_OWNER_ETH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: eth-network-goerli
                  key: contract-owner-eth-account-private-key
            - name: KEEP_CLIENT_ETH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: eth-account-privatekeys
                  key: account-2
            - name: ACCOUNTS_PRIVATE_KEYS
              value: $(CONTRACT_OWNER_ETH_PRIVATE_KEY),$(KEEP_CLIENT_ETH_PRIVATE_KEY)
            - name: KEEP_CLIENT_ETH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eth-account-info
                  key: account-2-address
          args:
            [
              "initialize",
              "--network",
              "goerli",
              "--owner",
              "$(KEEP_CLIENT_ETH_ADDRESS)",
              "--provider",
              "$(KEEP_CLIENT_ETH_ADDRESS)",
              "--operator",
              "$(KEEP_CLIENT_ETH_ADDRESS)",
            ]

---
apiVersion: v1
kind: Service
metadata:
  name: keep-client-2
  namespace: default
  labels:
    app: keep
    type: client
    id: "2"
spec:
  type: LoadBalancer
  ports:
    - port: 3919
      targetPort: 3919
      name: tcp-3919
    - port: 9601
      targetPort: 9601
      name: tcp-9601
    - port: 9701
      targetPort: 9701
      name: tcp-9701
  selector:
    app: keep
    type: client
    id: "2"
