buildTime = 2018-03-14T12:41:57.383Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "output"
linkPrefix = ""
author = "Keep Network"
license = "MIT"
name = "Keep Network Contracts Documentation"

[interaction]