---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    spec:
      securityContext:
        runAsUser: 472
        fsGroup: 472
      containers:
        - name: grafana
          image: grafana/grafana:9.1.7
          env:
            - name: GF_SERVER_DOMAIN
              value: monitoring.test.keep.network
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_FEATURE_TOGGLES_PUBLICDASHBOARDS
              value: "true"
          ports:
            - name: grafana
              containerPort: 3000
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: 500M
              cpu: "500m"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-dashboards-files
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-config-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-config-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-grafana-ini
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-dashboards-files
          configMap:
            name: grafana-dashboards
            defaultMode: 420
        - name: grafana-config-datasources
          configMap:
            name: grafana-config
            defaultMode: 420
            items:
              - key: datasources.yaml
                path: datasources.yaml
        - name: grafana-config-dashboards
          configMap:
            name: grafana-config
            defaultMode: 420
            items:
              - key: dashboards.yaml
                path: dashboards.yaml
        - name: grafana-grafana-ini
          configMap:
            name: grafana-config
            defaultMode: 0644
            items:
              - key: grafana.ini
                path: grafana.ini
