name: Go

#TODO: extend the conditions once workflow gets tested together with other workflows 
on:  
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true # ignore the failure of a step and avoid terminating the job
      - name: Run Docker build
        run: |
          docker build \
            --target gobuild \
            --tag go-build-env .
          docker build \
            --tag keep-client . 
      - name: Create and enter test results directory
        run: |
          mkdir -p /tmp/test-results/keep-core-go
          cd /tmp/test-results/keep-core-go/
      - name: DEBUG
        run: |
          pwd
      - name: DEBUG
        run: |
          ls
      - name: DEBUG
        run: |
          ls /tmp/test-results/keep-core-go/
      - name: DEBUG
        run: |
          ls /home/runner/work/keep-core/keep-core
      - name: Run Go tests
        run: |
          docker run \
            --volume /tmp/test-results/keep-core-go:/mnt/test-results \
            --workdir /go/src/github.com/keep-network/keep-core \
            go-build-env \
            gotestsum --junitfile /mnt/test-results/unit-tests.xml
      - name: DEBUG
        run: |
          pwd
      - name: DEBUG
        run: |
          ls
      - name: DEBUG
        run: |
          ls /tmp/test-results/keep-core-go/
      - name: DEBUG
        run: |
          ls /home/runner/work/keep-core/keep-core
      - name: Publish Unit Test results
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always() # guarantees that this action always runs, even if earlier steps fail
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files:  unit-tests.xml
          check_name: Go Test Results # name under which test results will be presented in GitHub (optional)