name: Go

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "infrastructure/**"
      - "scripts/**"
      - "token-stakedrop/**"
      - "solidity/dashboard/**"
  pull_request:
  workflow_dispatch:

jobs:
  client-detect-changes:
    runs-on: ubuntu-latest
    outputs:
      path-filter: ${{ steps.filter.outputs.path-filter }}
    steps:
    - uses: actions/checkout@v2
      if: github.event_name == 'pull_request' 
    - uses: dorny/paths-filter@v2
      if: github.event_name == 'pull_request' 
      id: filter
      with:
        filters: |
          path-filter:
            - './!((docs|infrastructure|scripts|token-stakedrop|(solidity/dashboard))/**)'

  client-build-test-publish:
    needs: client-detect-changes
    if: |
      github.event_name != 'pull_request'
        || needs.client-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Load environment variables
        uses: keep-network/load-env-variables@main # TODO: use @v1 once availible
        env: 
          CI_GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          environment: 'ropsten'
          ref: 'master'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Build Image
        uses: docker/build-push-action@v2
        with:
          target: gobuild
          tags: go-build-env
          build-args: |
            REVISION=${{ github.sha }}
          # VERSION= ? TODO: Configure version, sample: 1.7.6
          load: true # load image to local registry to use it in next steps
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run Go tests
        run: |
          docker run \
            --workdir /go/src/github.com/keep-network/keep-core \
            go-build-env \
            gotestsum

      - name: Login to Google Container Registry
        if: | # TODO: remove 'rfc-18' condition one tested
          (github.ref == 'refs/heads/master'
            && github.event_name != 'pull_request')
            || github.ref == 'refs/heads/rfc-18/load-env-var'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GCR_REGISTRY_URL }}
          username: _json_key
          password: ${{ secrets.KEEP_TEST_GCR_JSON_KEY }}

      - name: Build and publish Docker Runtime Image
        uses: docker/build-push-action@v2
        env:
          IMAGE_NAME: 'keep-client'
        with:
          # GCR image should be named according to following convention:
          # HOSTNAME/PROJECT-ID/IMAGE:TAG
          # We don't use TAG yet, will be added at later stages of work on RFC-18.
          tags: ${{ env.GCR_REGISTRY_URL }}/${{ env.GOOGLE_PROJECT_ID }}/${{ env.IMAGE_NAME }}
          labels: revision=${{ github.sha }}
          push: | # TODO: remove 'rfc-18' condition one tested
            ${{ (github.ref == 'refs/heads/master'
              && github.event_name != 'pull_request')
              || github.ref == 'refs/heads/rfc-18/load-env-var' }}

  client-scan:
    needs: client-detect-changes
    if: |
      github.event_name != 'pull_request'
        || needs.client-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - uses: securego/gosec@master
        with:
          args: |
            -exclude-dir=pkg/chain/gen
            ./...