name: Relay request submitter

on:
  # TODO: Uncomment once development is done
  # schedule:
  #  - cron: '*/30 * * * *'
  workflow_dispatch:
  push:

jobs:
  submit-relay-request:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: 'npm'
          cache-dependency-path: solidity/package-lock.json

      - run: npm ci

      - name: Install external keep-core contracts
        env:
          KEEP_CORE_VERSION: latest #TODO: Change to `ropsten`
        run: |
          mkdir external && cd "$_"
          npm init -y
          npm install --quiet --save-exact \
            @keep-network/keep-core@$KEEP_CORE_VERSION
          mkdir -p ../build/contracts
          cp -a node_modules/@keep-network/keep-core/artifacts/. ../build/contracts/

      - name: Submit relay entry request
        env:
          CHAIN_API_URL: ${{ secrets.KEEP_TEST_ETH_HOSTNAME_WS }}
          CONTRACT_OWNER_ACCOUNT_PRIVATE_KEY: |
            ${{ secrets.KEEP_TEST_ETH_CONTRACT_OWNER_PRIVATE_KEY }}
          WATCH_RELAY_ENTRY: true
        run: npx truffle exec ./scripts/request-relay-entry.js --network $TRUFFLE_NETWORK



